### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by emresaracoglu** [ChristophWurst/contactsmenu_social#1]
Hi @ChristophWurst 

This morning I saw only the license file on this project and now I see other files :) I'm curious about this project, is not this a Nextcloud application?

**Comment by ChristophWurst** [comment]
Hey :)

This is part of a new feature of the Nextcloud server: https://github.com/nextcloud/server/pull/3233#issuecomment-291190863

**Comment by emresaracoglu** [comment]
that it looks good!

**Comment by ChristophWurst** [comment]
hehe thx :) I'm closing this ticket now. You can also reach me and others on our IRC channel #nextcloud and #nextcloud-dev on freenode (only if we're online ofc) 😉
